export default class WeatherConstants{

  static readonly SERVER: string = 'https://devapi.qweather.com';

  static readonly WEATHER_NOW: string = 'v7/weather/now';

  static readonly CITY_LOOKUP: string = 'v2/city/lookup';

  static readonly LIFE_INDEX: string = 'v7/indices/1d';

  static readonly AIR_INDEX: string = 'v7/air/now';

  static readonly HOUR_FORECAST: string = 'v7/weather/24h';

  static readonly TENDAYS_FORECAST: string = 'v7/weather/10d';

  static readonly KEY: string = '5ee9a62041aa47a9a28f3a86d9f5ff02';


}

